### PR TITLE
Add continuous scan option

### PR DESCRIPTION
**Pull request by dbenninger**
By default, the `onDiscovered` callback is called only once for each discovered peripheral. If the `continuous` option is set to true, onDiscovered is called continuously, for each received advertising on Android or as often as iOS reports it.

### CODE REVIEW

**Comment by damikael** [comment]
Good, just what i need! While it's not yet merged, how can I compile and use it in my project? Thanks

**Comment by damikael** [comment]
Perfect, thanks @dbenninger

**Comment by mgerdt** [comment]
Hi there,
any news on merging the "continuous" option into the master branch?
Thanks in advance

**Comment by farfromrefug** [comment]
this is now the default. The old behavior can be handled o the app side

**Pull request closed without merging**
